# Generated by Django 3.0.7 on 2020-07-05 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='todo',
        ),
    ]
