# Generated by Django 3.0.7 on 2020-07-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
                ('semail', models.CharField(max_length=50)),
                ('scity', models.CharField(max_length=120)),
            ],
        ),
    ]
