# Generated by Django 3.0.7 on 2020-07-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sage',
            field=models.IntegerField(null=True),
        ),
    ]
